### PR TITLE
"Add contact us page layout"

### PR DESCRIPTION
**Pull request by Roohan0004**
Added contact us pages for html and CSS files.

### CODE REVIEW

**Comment by ghost** [comment]
"This 2nd line in code  could be improved by adding a default value for the color property to avoid errors."

**Review by ghost — APPROVED** [review]

**Review by nawafmalikk — APPROVED** [review]
Seems alright

**Review by ghost — COMMENTED** [review]
correct

**Review by Roohan0004 — COMMENTED** [review]
correct

**Review by nawafmalikk — COMMENTED** [review]
alright

**Pull request merged**
