### PR TITLE
"Add Home page html file and CSS file"

### PR DESCRIPTION
**Pull request by ghost**
Add Home page html file and CSS file.

### CODE REVIEW

**Review by Roohan0004 — APPROVED** [review]
code is bug free

**Review by nawafmalikk — APPROVED** [review]
code is correct

**Review by nawafmalikk — COMMENTED** [review]
correct

**Review by ghost — COMMENTED** [review]
correct

**Review by Roohan0004 — COMMENTED** [review]
correct

**Review by nawafmalikk — COMMENTED** [review]
correct

**Pull request merged**
